# Generated by Django 2.2.2 on 2019-07-21 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190721_1014'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='post_hit',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
