# Generated by Django 2.2.2 on 2019-07-21 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_about_post_hit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'ordering': ['-id']},
        ),
    ]
