# Generated by Django 2.2.2 on 2019-08-07 11:41

from django.db import migrations, models
import hitcount.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20190806_2231'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maplocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placename', models.CharField(max_length=50)),
                ('address', models.CharField(blank=True, max_length=50)),
                ('phonenumber', models.CharField(blank=True, max_length=20)),
                ('lat', models.CharField(max_length=50)),
                ('lng', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Post_count',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            bases=(models.Model, hitcount.models.HitCountMixin),
        ),
    ]
